### ISSUE TITLE
prebuilt binaries all output "simstrat version 2.0"

### ISSUE THREAD

**Issue by zimmermm** [Eawag-AppliedSystemAnalysis/Simstrat#26]

**Comment by zimmermm** [comment]
haven't checked all versions but 1.6 prints "Simstrat version 2.0" to the console
The current version 2.1.2 prints "Simstrat version 2.1" which is also true but not the whole truth..

**Comment by Diftin** [comment]
I created branches from the original tags of versions 2.1, 2.1.1 and 2.1.2, changed the version number on these respective branches and then reset the tag at the end of these branches. So the issue is solved now for these versions. Version 1.6 is another problem as the code this tag points to is actually version 2.0...
